apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testproj-ingress
  namespace: testproj
spec:
  ingressClassName: traefik
  rules:
    - host: testproj.zzyra.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: testproj-active
                port:
                  number: 80
